name: memorizador_cartas
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  progress_dialog: ^1.2.4
  hasura_connect: ^1.2.1+1
  spinner: ^1.0.1
  flutter_staggered_grid_view: ^0.3.2
  get: 
    git:
      url: https://github.com/jonataslaw/getx.git
      ref: dev
  dio: ^3.0.10
  flutter_mobx: ^0.3.3+3
  mobx: ^0.3.9+3
  bloc_pattern: ^2.5.1
  msk_utils:
    git:
      url: git@github.com:ReniDelonzek/msk_utils.git
      ref: b92f09cb908ca77f5561df621802eca7ac1b69d4
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  mobx_codegen: ^0.3.10+1
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imagens/

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean: flutter pub run build_runner clean 
  compilar: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
  profile: flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --profile
